server:
  port: 8898

spring:
  data:
    neo4j:
      uri: bolt://120.79.66.30:7687
      username: neo4j
      password: neo4j123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  thymeleaf:
    check-template: false
    check-template-location: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true


#file:
#  doc-dir: file/
#
#path:
#  video-upload-path: "C:/opt/ZhanXin/videos/"
#  picture-upload-path: "C:/opt/ZhanXin/images/"
